version: "3.8"
services:
  nginx:
    build:
    ports:
      - "80:80"
    depends_on:
      - weatherapp_backend
      - weatherapp_frontend
  weatherapp_backend:
    build: ./backend
    ports:
        - "9000:9000"
  weatherapp_frontend:
      build: ./frontend
      ports:
        - "8000:8000"
      environment:
        - ENDPOINT=http://localhost:9000/api
      depends_on:
        - weatherapp_backend
