- hosts: all
  gather_facts: no
  tasks:
    - name: Install python3 for Ansible
      raw: sudo apt-get update && sudo apt-get install -y python3 python3-apt

- name: weather app
  hosts: all 
  become: yes

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    app_repo: "https://github.com/koowyzrk/efi-recruitment-2025-solution"
    app_dir: "/opt/weather_app"

  tasks:
    - name: apt update and install system packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Install Docker from Debian repo
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose Plugin
      ansible.builtin.apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Install python3-docker package via apt
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: yes

    - name: create app dir
      ansible.builtin.file:
        path: "{{app_dir}}"
        state: directory
        mode: '0755'

    - name: clone repository
      ansible.builtin.git:
        repo: "{{app_repo}}"
        dest: "{{app_dir}}"
        version: main
        update: yes

    - name: add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Run docker-compose up
      ansible.builtin.command:
        cmd: docker-compose up -d --build
        chdir: "{{ app_dir }}"
